### ISSUE TITLE
Get micro-controller talking to the gryo

### ISSUE THREAD

**Issue by skylar** [CoderDojoGitHub/robot1-series#9]
This is a great goal for March 18.

**Comment by skylar** [comment]
@jonmagic what are you using to help guide you through the gyro intro?  I'm going to collect some links here:

Breakout board overviews (I have the GY-521):
    http://playground.arduino.cc/Main/MPU-6050

Tutorial (sorta):
    http://www.botched.co.uk/pic-tutorials/mpu6050-setup-data-aquisition/

Code LIbs:
    http://www.i2cdevlib.com/devices/mpu6050#source

**Comment by jonmagic** [comment]
I2C scanner: http://playground.arduino.cc/Main/I2cScanner

Some board/chip description and code: http://www.geeetech.com/wiki/index.php/MPU-6050_Triple_Axis_Accelerometer_%26_Gyro_Breakout

**Comment by skylar** [comment]
Ported Spark lib:  https://github.com/pkourany/MPU6050Spark

**Comment by skylar** [comment]
Good news, I got both versions working, raw and DMP.  I had jumbled my includes a bit, but also the cloud compiler seemed to not like what he had in his repo exactly for that one.  In any case, a couple steps to getting the DMP version running:
-  make sure to attach an interrupt wire to the board (the example configured pin "0" which is D0 on the spark, but since our I2C bus is there, I put it on A0 instead).
-  the spark-cli serial monitor didn't seem to bind to the serial on this one.  I had to use screen and match the baud configured in the client.
-  you probably won't catch the serial start so hit any key after connecting to launch the demo

I'll try and jigger the code around to make the demo easier to work with, but next step is to start porting the robot code and the other related libs.  Exciting!

**Comment by jonmagic** [comment]
:sparkles: what is the interrupt wire for?

**Comment by jonmagic** [comment]
:sparkles: what is the interrupt wire for?

**Comment by jonmagic** [comment]
@skylar could you share the DMP code you got working? I can't get the dmp code from the link above to compile in the web IDE or from the cli.
